"""initial schema

Revision ID: 3fa63fbe0dd9
Revises: 
Create Date: 2026-08-11 19:44:15.675813
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3fa63fbe0dd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_user_id', sa.String(length=64), nullable=False),
    sa.Column('screen_name', sa.String(length=200), nullable=True),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('default_rating', sa.String(length=8), nullable=True),
    sa.Column('default_content_type', sa.String(length=16), nullable=True),
    sa.CheckConstraint("default_content_type IS NULL OR default_content_type IN ('illust', 'irl', 'mod', 'ai', 'other')", name='ck_default_content_type'),
    sa.CheckConstraint("default_rating IS NULL OR default_rating IN ('sfw', 'r18')", name='ck_default_rating'),
    sa.CheckConstraint("role IS NULL OR role IN ('main', 'alt', 'r18_alt')", name='ck_role'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_user_id', name='uq_account_platform_user')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_creator', ['creator_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_post_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('is_retweet', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=True),
    sa.Column('content_type', sa.String(length=16), nullable=True),
    sa.Column('rating_source', sa.String(length=16), nullable=True),
    sa.CheckConstraint("content_type IS NULL OR content_type IN ('illust', 'irl', 'mod', 'ai', 'other')", name='ck_content_type'),
    sa.CheckConstraint("rating IS NULL OR rating IN ('sfw', 'r18')", name='ck_rating'),
    sa.CheckConstraint("rating_source IS NULL OR rating_source IN ('manual', 'account_default', 'auto')", name='ck_rating_source'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_post_id', name='uq_post_platform_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('ix_posts_account', ['account_id'], unique=False)
        batch_op.create_index('ix_posts_rating', ['rating'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('platform_media_key', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('photo', 'video', 'animated_gif')", name='ck_kind'),
    sa.CheckConstraint("status IN ('pending', 'downloading', 'done', 'failed')", name='ck_status'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'ordinal', name='uq_media_post_ordinal')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index('ix_media_hash', ['file_hash'], unique=False)
        batch_op.create_index('ix_media_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('ix_media_status')
        batch_op.drop_index('ix_media_hash')

    op.drop_table('media')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_rating')
        batch_op.drop_index('ix_posts_account')

    op.drop_table('posts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_creator')

    op.drop_table('accounts')
    op.drop_table('creators')
    # ### end Alembic commands ###
